//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public Proyecto()
        {
            this.Factor = new HashSet<Factor>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public short idGerente { get; set; }
        public string Descripcion { get; set; }
        public short GerenteId { get; set; }
    
        public virtual ICollection<Factor> Factor { get; set; }
        public virtual Gerente Gerente { get; set; }
    }
}
