USE [master]
GO

/****** Object:  Database [tp_punto_net]    Script Date: 16/05/2014 23:05:00 ******/
CREATE DATABASE [tp_punto_net]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tp_punto_net', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\tp_punto_net.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'tp_punto_net_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\tp_punto_net_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [tp_punto_net] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tp_punto_net].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tp_punto_net] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tp_punto_net] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tp_punto_net] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tp_punto_net] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tp_punto_net] SET ARITHABORT OFF 
GO

ALTER DATABASE [tp_punto_net] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [tp_punto_net] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [tp_punto_net] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tp_punto_net] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tp_punto_net] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tp_punto_net] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tp_punto_net] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tp_punto_net] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tp_punto_net] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tp_punto_net] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tp_punto_net] SET  ENABLE_BROKER 
GO

ALTER DATABASE [tp_punto_net] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tp_punto_net] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tp_punto_net] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tp_punto_net] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tp_punto_net] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tp_punto_net] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tp_punto_net] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tp_punto_net] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [tp_punto_net] SET  MULTI_USER 
GO

ALTER DATABASE [tp_punto_net] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tp_punto_net] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tp_punto_net] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tp_punto_net] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [tp_punto_net] SET  READ_WRITE 
GO

